### ISSUE TITLE
Title character limit is too short

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/osTicket#10]
Character limit for title field is 30. 
This way too short. Go for a 60 please.
<img width="1199" alt="capture d ecran 2018-10-17 a 14 38 16" src="https://user-images.githubusercontent.com/11473995/47086582-34b41580-d21a-11e8-9b0d-8c9afa2da991.png">

**Comment by lu-hamani** [comment]
Limit has been upgraded to 60
